# Bibliotecas

In [1]:
import numpy as np

from scipy.stats import multivariate_normal

# Funções

Essas funções possuem o objetivo de criar dados sinteticos intervalares em três grupos. Sua saida será 8 conjunto de dados, cada um com sua confiuguração referentes ao artigo  Agrupamento e regressão linear de dados simbólicos intervalares baseados em novas representações
por: SOUZA, Leandro Carlos de
Instituição de Defesa: (2016).

## Função geradora de sementes Bivariada.

In [4]:
## Funções geradora de sementes.

def gerador_semente1():
  random_seed = 2
  
  # Grupo 1
  cov_val1 = [[100, 0], [0,25]] # Matriz de variacia grupo 1 semente 2
  media1 = [25,10] # Matriz de medias grupo 1 semente 2
  distr1 = multivariate_normal(cov = cov_val1, mean = media1, seed = random_seed) 
  data1 = distr1.rvs(size = 150) # Gerando dados bivariado gaussianos de tamanho 150.

  # Grupo 2
  cov_val2 = [[36, 0], [0,144]] # Matriz de variacia grupo 2 semente 2
  media2 = [60, 30] # Matriz de medias grupo 2 semente 2
  distr2 = multivariate_normal(cov = cov_val2, mean = media2, seed = random_seed)
  data2 = distr2.rvs(size = 150) # Gerando dados bivariado gaussianos de tamanho 150.

  # Grupo 3
  cov_val3 = [[16, 0], [0,16]] # Matriz de variacia grupo 3 semente 2
  media3 = [20,40] # Matriz de medias grupo 3 semente 2
  distr3 = multivariate_normal(cov = cov_val3, mean = media3, seed = random_seed)
  data3 = distr3.rvs(size = 50) # Gerando dados bivariado gaussianos de tamanho 50.

  Semente1 = np.concatenate((data1, data2 ,data3), axis=0)

  return Semente1


def gerador_semente2():
  random_seed = 2
  
  # Grupo 1
  cov_val4 = [[100, 0], [0,25]] # Matriz de variacia grupo 1 semente 2
  media4 = [30,10] # Matriz de medias grupo 1 semente 2
  distr4 = multivariate_normal(cov = cov_val4, mean = media4, seed = random_seed) 
  data4 = distr4.rvs(size = 150) # Gerando dados bivariado gaussianos de tamanho 150.

  # Grupo 2
  cov_val5 = [[36, 0], [0,144]] # Matriz de variacia grupo 2 semente 2
  media5 = [50, 30] # Matriz de medias grupo 2 semente 2
  distr5 = multivariate_normal(cov = cov_val5, mean = media5, seed = random_seed)
  data5 = distr5.rvs(size = 150) # Gerando dados bivariado gaussianos de tamanho 150.

  # Grupo 3
  cov_val6 = [[16, 0], [0,16]] # Matriz de variacia grupo 3 semente 2
  media6 = [30,35] # Matriz de medias grupo 3 semente 2
  distr6 = multivariate_normal(cov = cov_val6, mean = media6, seed = random_seed)
  data6 = distr6.rvs(size = 50) # Gerando dados bivariado gaussianos de tamanho 50.

  Semente2 = np.concatenate((data4, data5,data6), axis=0)

  return Semente2

## Função geradora de configuração

In [10]:
def conjunto_config1(Semente1, classes0):
  data_sync_1_1 = np.zeros([350,4]) # Criando o conjunto 350x4 zerado.

  # Configuração 1
  for i in range(350):
    for j in range(0,4,2):
      if classes0[i] == 0:
        x = int(j/2)
        intervalo = np.random.randint(low = 1, high = 10, size = 1)
        data_sync_1_1[i][j] = Semente1[i][x] - (intervalo/2)
        data_sync_1_1[i][j+1] = Semente1[i][x] + (intervalo/2)
      elif classes0[i] == 1:
        x = int(j/2)
        intervalo = np.random.randint(low = 1, high = 10, size = 1)
        data_sync_1_1[i][j] = Semente1[i][x] - (intervalo/2)
        data_sync_1_1[i][j+1] = Semente1[i][x] + (intervalo/2)
      elif classes0[i] == 2:
        x = int(j/2)
        intervalo = np.random.randint(low = 1, high = 10, size = 1)
        data_sync_1_1[i][j] = Semente1[i][x] - (intervalo/2)  
        data_sync_1_1[i][j+1] = Semente1[i][x] + (intervalo/2)
    
  return data_sync_1_1

def conjunto_config2(Semente1, classes0):
  data_sync_1_2 = np.zeros([350,4])

  # Configuração 2
  for i in range(350):
    for j in range(0,4,2):
      if classes0[i] == 0:
        if j == 0:
          x = int(j/2)
          intervalo = np.random.randint(low = 3, high = 7, size = 1)
          data_sync_1_2[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_2[i][j+1] = Semente1[i][x] + (intervalo/2)
        else:
          x = int(j/2)
          intervalo = np.random.randint(low = 5, high = 8, size = 1)
          data_sync_1_2[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_2[i][j+1] = Semente1[i][x] + (intervalo/2)

      elif classes0[i] == 1:
        if j == 0:
          x = int(j/2)
          intervalo = np.random.randint(low = 3, high = 7, size = 1)
          data_sync_1_2[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_2[i][j+1] = Semente1[i][x] + (intervalo/2)
        else:
          x = int(j/2)
          intervalo = np.random.randint(low = 5, high = 8, size = 1)
          data_sync_1_2[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_2[i][j+1] = Semente1[i][x] + (intervalo/2)
      elif classes0[i] == 2:
        if j == 0:
          x = int(j/2)
          intervalo = np.random.randint(low = 3, high = 7, size = 1)
          data_sync_1_2[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_2[i][j+1] = Semente1[i][x] + (intervalo/2)
        else:
          x = int(j/2)
          intervalo = np.random.randint(low = 5, high = 8, size = 1)
          data_sync_1_2[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_2[i][j+1] = Semente1[i][x] + (intervalo/2)
  return data_sync_1_2

def conjunto_config3(Semente1, classes0):
  data_sync_1_3 = np.zeros([350,4])

  # Configuração 3
  for i in range(350):
    for j in range(0,4,2):
      if classes0[i] == 0:
        if j == 0:
          x = int(j/2)
          intervalo = np.random.randint(low = 1, high = 4, size = 1)
          data_sync_1_3[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_3[i][j+1] = Semente1[i][x] + (intervalo/2)
        else:
          x = int(j/2)
          intervalo = np.random.randint(low = 1, high = 4, size = 1)
          data_sync_1_3[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_3[i][j+1] = Semente1[i][x] + (intervalo/2)

      elif classes0[i] == 1:
        if j == 0:
          x = int(j/2)
          intervalo = np.random.randint(low = 3, high = 7, size = 1)
          data_sync_1_3[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_3[i][j+1] = Semente1[i][x] + (intervalo/2)
        else:
          x = int(j/2)
          intervalo = np.random.randint(low = 3, high = 7, size = 1)
          data_sync_1_3[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_3[i][j+1] = Semente1[i][x] + (intervalo/2)
      elif classes0[i] == 2:
        if j == 0:
          x = int(j/2)
          intervalo = np.random.randint(low = 5, high = 10, size = 1)
          data_sync_1_3[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_3[i][j+1] = Semente1[i][x] + (intervalo/2)
        else:
          x = int(j/2)
          intervalo = np.random.randint(low = 5, high = 10, size = 1)
          data_sync_1_3[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_3[i][j+1] = Semente1[i][x] + (intervalo/2)
      
  return data_sync_1_3

def conjunto_config4(Semente1, classes0):
  data_sync_1_4 = np.zeros([350,4])

  # Configuração 4
  for i in range(350):
    for j in range(0,4,2):
      if classes0[i] == 0:
        if j == 0:
          x = int(j/2)
          intervalo = np.random.randint(low = 4, high = 7, size = 1)
          data_sync_1_4[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_4[i][j+1] = Semente1[i][x] + (intervalo/2)
        else:
          x = int(j/2)
          intervalo = np.random.randint(low = 1, high = 3, size = 1)
          data_sync_1_4[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_4[i][j+1] = Semente1[i][x] + (intervalo/2)

      elif classes0[i] == 1:
        if j == 0:
          x = int(j/2)
          intervalo = np.random.randint(low = 1, high = 2, size = 1)
          data_sync_1_4[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_4[i][j+1] = Semente1[i][x] + (intervalo/2)
        else:
          x = int(j/2)
          intervalo = np.random.randint(low = 6, high = 9, size = 1)
          data_sync_1_4[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_4[i][j+1] = Semente1[i][x] + (intervalo/2)
      elif classes0[i] == 2:
        if j == 0:
          x = int(j/2)
          intervalo = np.random.randint(low = 2, high = 3, size = 1)
          data_sync_1_4[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_4[i][j+1] = Semente1[i][x] + (intervalo/2)
        else:
          x = int(j/2)
          intervalo = np.random.randint(low = 3, high = 6, size = 1)
          data_sync_1_4[i][j] = Semente1[i][x] - (intervalo/2)
          data_sync_1_4[i][j+1] = Semente1[i][x] + (intervalo/2)
  return data_sync_1_4

## Função geradora dos dados sinteticos intervalar

In [6]:
def conjunto_dados_sinteticos():
  # Definindo as classes.
  classes0 = np.zeros(350)
  for i in range(350):
    if i < 150:
      classes0[i] = 0
    elif i < 300 and i > 149:
      classes0[i] = 1
    elif i < 350 and i > 299:
      classes0[i] = 2
  
  # Gerando as sementes
  semente1 = gerador_semente1()
  semente2 = gerador_semente2()

  # Gerador de dados config 1 a 4 - Semente 1
  conjunto1 = conjunto_config1(semente1, classes0)
  conjunto2 = conjunto_config1(semente1, classes0)
  conjunto3 = conjunto_config1(semente1, classes0)
  conjunto4 = conjunto_config1(semente1, classes0)

  # Gerador de dados config 5 a 8 - Semente 2
  conjunto5 = conjunto_config1(semente2, classes0)
  conjunto6 = conjunto_config1(semente2, classes0)
  conjunto7 = conjunto_config1(semente2, classes0)
  conjunto8 = conjunto_config1(semente2, classes0)

  return conjunto1, conjunto2, conjunto3, conjunto4, conjunto5, conjunto6, conjunto7, conjunto8

# Teste

In [11]:
conjunto1, conjunto2, conjunto3, conjunto4, conjunto5, conjunto6, conjunto7, conjunto8 = conjunto_dados_sinteticos()

In [13]:
# Visualizando o conjunto de dados na primeira configuração.

print(conjunto1)

[[19.83242153 21.83242153  5.71866586 13.71866586]
 [ 0.13803904  7.13803904 15.70135404 20.70135404]
 [ 6.56564415  7.56564415  3.79126317  7.79126317]
 ...
 [10.04816198 16.04816198 41.66329581 46.66329581]
 [20.52188788 22.52188788 38.63145893 39.63145893]
 [22.19412599 27.19412599 26.12558724 35.12558724]]
